### ISSUE TITLE
安装依赖出错

### ISSUE THREAD

**Issue by sayri23** [fz6m/opqqq-plugin#10]
请问怎么解决？
![Screenshot_2021-04-05-19-57-48-52_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/62638560/113580322-23fcf180-9658-11eb-9258-2e8057bccf43.jpg)

**Comment by fz6m** [comment]
看下安装 sdk 的说明，有问题直接看文档就好了

https://fz6m.github.io/opqqq-plugin-press/guide/guide.html
