### ISSUE TITLE
Strings签到和Vtuber运势不好使

### ISSUE THREAD

**Issue by howrain** [fz6m/opqqq-plugin#2]
两个功能都是只有在重启后第一次调用可以，但是第二次调用机器人完全不会回复，后台也有接收到消息

**Comment by fz6m** [comment]
抽签多了就不灵了，抽多次的都是屑

**Comment by fz6m** [comment]
每天只能抽一次，需要多次请把 user 里的用户 qq 号文件删掉。

有多次的需求可以下载 beta 分支的 小狐狸签 无限版

**Comment by howrain** [comment]
哦这样啊2333
