### ISSUE TITLE
时不时会出现签到出错

### ISSUE THREAD

**Issue by pudding233** [fz6m/opqqq-plugin#4]
` File "/home/pi/Desktop/OPQBOT/OPQBot_3.0.8_linux_arm/python/plugins/bot_sign_in.py", line 66, in receive_group_msg
    mainProgram(msg, bot, userQQ, userGroup, nickname)
    │           │    │    │       │          └ 'pudding233 【即将开学】'
    │           │    │    │       └ 1072915340
    │           │    │    └ 2480751781
    │           │    └ <iotbot.action.Action object at 0x74e95bb0>
    │           └ '签到'
    └ <function mainProgram at 0x74977588>

  File "/home/pi/Desktop/OPQBOT/OPQBot_3.0.8_linux_arm/python/plugins/bot_sign_in.py", line 610, in mainProgram
    result = processing(userQQ, nickname)
             │          │       └ 'pudding233 【即将开学】'
             │          └ 2480751781
             └ <function processing at 0x74983420>

  File "/home/pi/Desktop/OPQBOT/OPQBot_3.0.8_linux_arm/python/plugins/bot_sign_in.py", line 679, in processing
    result = generatePicture(userQQ, nickname, userInfo.favorability, userInfo.days, hitokoto)
             │               │       │         │                      │              └ '相逢一醉是前缘，风雨散、飘然何处。'
             │               │       │         │                      └ {'days': 4, 'last_time': '2020-08-17', 'favorability': '93'}
             │               │       │         └ {'days': 4, 'last_time': '2020-08-17', 'favorability': '93'}
             │               │       └ 'pudding233 【即将开学】'
             │               └ 2480751781
             └ <function generatePicture at 0x74983390>

  File "/home/pi/Desktop/OPQBOT/OPQBot_3.0.8_linux_arm/python/plugins/bot_sign_in.py", line 648, in generatePicture
    result = SignIn(userQQ, nickname, favorability, days, hitokoto).drawing()
             │      │       │         │             │     └ '相逢一醉是前缘，风雨散、飘然何处。'
             │      │       │         │             └ 4
             │      │       │         └ '93'
             │      │       └ 'pudding233 【即将开学】'
             │      └ 2480751781
             └ <class 'plugins.bot_sign_in.SignIn'>

  File "/home/pi/Desktop/OPQBOT/OPQBot_3.0.8_linux_arm/python/plugins/bot_sign_in.py", line 456, in drawing
    result = (self.createAvatar()
              │    └ <function SignIn.createAvatar at 0x74977bb8>
              └ <plugins.bot_sign_in.SignIn object at 0x7239ed10>

  File "/home/pi/Desktop/OPQBOT/OPQBot_3.0.8_linux_arm/python/plugins/bot_sign_in.py", line 311, in createAvatar
    self._img = self.resize(Image.open(BytesIO(res)).convert('RGBA'), (size, size))
    │    │      │    │      │     │    │       │                       │     └ 640
    │    │      │    │      │     │    │       │                       └ 640
    │    │      │    │      │     │    │       └ b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Foun...
    │    │      │    │      │     │    └ <class '_io.BytesIO'>
    │    │      │    │      │     └ <function open at 0x74be8e40>
    │    │      │    │      └ <module 'PIL.Image' from '/usr/lib/python3/dist-packages/PIL/Image.py'>
    │    │      │    └ <staticmethod object at 0x74979790>
    │    │      └ <plugins.bot_sign_in.SignIn object at 0x7239ed10>
    │    └ <Status.FAILURE: '_failure'>
    └ <plugins.bot_sign_in.SignIn object at 0x7239ed10>

  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2687, in open
    % (filename if filename else fp))
       │           │             └ <_io.BytesIO object at 0x72d9a090>
       │           └ ''
       └ ''

`
经常发生签到报错，但再次签到却正常

**Comment by fz6m** [comment]
获取头像的时候404了，检查下保证网络通畅吧

**Comment by pudding233** [comment]
> 获取头像的时候404了，检查下保证网络通畅吧

哦，好的，谢谢了
