### ISSUE TITLE
bot.py起不来

### ISSUE THREAD

**Issue by 24619** [fz6m/opqqq-plugin#5]
[root@hase Plugins]# chmod +rwx * -R
[root@hase Plugins]# python3 bot.py

+---------------------+-------+----------------------------------------------+
|       Receiver      | Count |                     Info                     |
+---------------------+-------+----------------------------------------------+
| Friend Msg Receiver |   0   |                                              |
| Group  Msg Receiver |   4   | pcr_fortune/sign_in/good_morning/throw_creep |
| Event      Receiver |   0   |                                              |
+---------------------+-------+----------------------------------------------+

2020-12-26 20:32:13 INFO    Connecting to the server...
❌ 2020-12-26 20:32:13 ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/iotbot/client.py", line 214, in run
    self.socketio.connect(self.config.address, transports=['websocket'])
  File "/usr/local/lib/python3.9/site-packages/python_socketio-5.0.3-py3.9.egg/socketio/client.py", line 280, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection error

报2个文件错误

**Comment by fz6m** [comment]
按使用教程看一下 sdk 是否已经安装好了。

再确认根目录的配置文件是否已经配置。

再确认 opq 跑在哪个端口上，端口是否和其他程序冲突。
