### ISSUE TITLE
可以使用botoy重建嘛

### ISSUE THREAD

**Issue by ChaseOnion** [fz6m/opqqq-plugin#6]
botoy是python-iotbot的新版本，拥有更好的兼容性，只更新了部分的名称和类
我准备自己改~但能力不允许（）~
~owo~

**Comment by fz6m** [comment]
> botoy是python-iotbot的新版本，拥有更好的兼容性，只更新了部分的名称和类
> 我准备自己改~但能力不允许（）~
> ~owo~

好的呢，有时间会考虑~
目前这个库运行也很稳定的，几个月都不会掉。

**Comment by ChaseOnion** [comment]
嗯嗯
# ~我提交这种issue你不会生气吧~
