### ISSUE TITLE
把原神运势那个插件放到自己机器人里运行报错

### ISSUE THREAD

**Issue by sayri23** [fz6m/opqqq-plugin#8]
如题，代码里bot＝action哪里直接填了机器人的QQ，from iotbot改成了botoy
![IMG_20210405_100200](https://user-images.githubusercontent.com/62638560/113529727-cc7a6980-95f6-11eb-8bb8-cedd7a21f92d.jpg)

**Comment by fz6m** [comment]
这个插件的 sdk 不是 botoy，辛苦仔细看下使用说明文档站吧 😅
